#!/bin/bash
#####

# Delete old snapshots
#sudo snapper cleanup timeline
sudo snapper cleanup number
sudo snapper cleanup empty-pre-post 

# Den Refresh sollte er alleine machen, aber sicher ist sicher
sudo zypper refresh
# Listet moegliche Updates auf
sudo zypper lu
# Der Update-Prozess
sudo zypper dup --no-allow-vendor-change -y 
# Falls eigentlich erwartete Software entfernt wurde
sudo zypper install-new-recommends

# Temporaere Dateien entfernen
sudo rm -rf /tmp/*

# Datenbank von locate aktualisieren
sudo updatedb

# TRIM funktioniert nur, wenn in 
# /etc/crypttab fuer die verschlusselten Platten die Option
# 'discard' eingetragen wurde.
# Ausserdem sollte in 
# /etc/fstab ebenfalls 'discard' gesetzt sein
# ... zumindest fuer XFS.
#printf "\n/home wird getrimmt..."
#sudo fstrim -v /home

# BTRFS balancer automatisieren
echo -e "/ default subvolume:"
sudo btrfs subvolume get-default /
echo -e "\n"
sudo systemctl restart btrfsmaintenance-refresh
sudo /usr/share/btrfsmaintenance/btrfs-balance.sh

echo -e "\n"
# BTRFS Belegung anzeigen
sudo btrfs fi df /

# Zeigt laufende Prozesse an, die von dem Update gestoert werden
# sein koennten, gibt eine Entscheidungshilfe, ob ein Neustart
# sinnvoll ist.
sudo zypper ps -s

# Verlassen...
sudo -k
exit 0
