#!/bin/bash
#####

# Delete old snapshots
#sudo snapper cleanup timeline
sudo snapper cleanup number
sudo snapper cleanup empty-pre-post

# backup, using the SpiderOak ONE backup tool …
# don't use --headless, it won't do the job (for me, at least)
# https://spideroak.support/hc/en-us/articles/115004794506
SpiderOakONE --batchmode --verbose;
# https://spideroak.support/hc/en-us/articles/115001893323
# keep one version per hour for the last 12 hours, one daily for
# 30 days, and one annual version for 30 years
SpiderOakONE --purge-historical-versions h12,d30,y30 --verbose;

# stop f*cking PackageKit from interfering the process
sudo systemctl stop packagekit
#sudo systemctl mask packagekit

# zypper should auto-refresh anyway, but hey …
sudo zypper refresh
# create an overview over all possible updates
sudo zypper lu
# best possible update command, I think
sudo zypper dup --no-allow-vendor-change -y
# re-installs default packages
#sudo zypper install-new-recommends

# Flatpak has its own update mechanism, of course …
sudo flatpak update --force-remove --assumeyes
sudo flatpak uninstall --unused --assumeyes
sudo flatpak repair

# now might be a good time to remove temporary files
sudo rm -rf /tmp/*
sudo rm -rf /var/tmp/*
sudo rm -rf /var/tmp/*
sudo rm -rf ~/.cache/evolution/tmp/*
sudo rm -rf ~/.cache/gnome-builder/tags/share/flatpak/repo/tmp/*

# makes the database behind 'locate'
sudo updatedb

# BTRFS balancer
echo -e "/ default subvolume:"
sudo btrfs subvolume get-default /
echo -e "\n"
sudo systemctl restart btrfsmaintenance-refresh
sudo /usr/share/btrfsmaintenance/btrfs-balance.sh

# show the remaining BTRFS snapshots
sudo snapper list

# show how much disk space the BTRFS partition really occupies
echo -e "\n"
sudo btrfs fi df /

# show orphaned packages (do after upgrade)
# see https://doc.opensuse.org/documentation/leap/reference/html/book-reference/cha-sw-cl.html#sec-zypper-softup-orphaned
#sudo zypper packages --orphaned
#sudo zypper packages --unneeded

# show if some processes are running that were update right now (→ restart)
sudo zypper ps -s

# leave the super-user shell …
sudo -k
exit 0
